version: '2'
services:
  mc6007t1-app:
    image: mc6007t1
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://mc6007t1-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=mc6007t1
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  mc6007t1-mongodb:
    extends:
      file: mongodb.yml
      service: mc6007t1-mongodb
